# Dockerfile

# Use the official PHP 8.2 FPM image
FROM php:8.2-fpm

# Install Nginx
RUN apt-get update && apt-get install -y \
    software-properties-common \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    libicu-dev \
    libpq-dev \
    git \
    unzip \
    curl \
    # Install PHP extensions
    && docker-php-ext-install \
    gd \
    mbstring \
    xml \
    zip \
    pdo \
    pdo_mysql \
    mysqli \
    && pecl install mongodb redis \
    && docker-php-ext-enable mongodb redis \
    # Clean up
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Download and install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


# Expose ports
EXPOSE 80

# Start Nginx and PHP-FPM
CMD php-fpm
