# Use an official Ubuntu 22.04 as a base image
FROM node:22

# Maintainer information
LABEL maintainer="RFGONZALES12@gmail.com"

# Set environment variables
ENV SHELL=/bin/bash \
    LANG=en_US.utf8 \
    LC_ALL=C.UTF-8

# Set locale to UTF-8 and install necessary packages
# Set locale to UTF-8 and install necessary packages and PHP extension

# Set the working directory
WORKDIR /var/www/html


# Expose port 80
EXPOSE 3000 5173 13714

# Use the default command provided by the base image to start Apache
# Command to keep the container running
CMD ["tail", "-f", "/dev/null"]