# Use an official Ubuntu 22.04 as a base image
FROM php:8.2-cli

# Maintainer information
LABEL maintainer="RFGONZALES12@gmail.com"

# Set environment variables
ENV SHELL=/bin/bash \
    LANG=en_US.utf8 \
    LC_ALL=C.UTF-8

# Set locale to UTF-8 and install necessary packages
# Set locale to UTF-8 and install necessary packages and PHP extensions
RUN apt-get update \
    && apt-get install -y \
    software-properties-common \
    libzip-dev \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libonig-dev \
    libxml2-dev \
    libcurl4-openssl-dev \
    libicu-dev \
    libpq-dev \
    git \
    unzip \
    curl \
    # Install PHP extensions
    && docker-php-ext-install \
    gd \
    mbstring \
    xml \
    zip \
    pdo \
    pdo_mysql \
    mysqli \
    && pecl install mongodb redis \
    && docker-php-ext-enable mongodb redis \
    # Clean up
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*



# Download and install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer


# Set the working directory
WORKDIR /var/www/html


# Expose port 80
EXPOSE 8000 80

# Use the default command provided by the base image to start Apache
# Command to keep the container running
CMD ["tail", "-f", "/dev/null"]